name: kaonic
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

  #state management
  flutter_bloc: ^8.1.6
  stream_transform: ^2.1.0
  rxdart: ^0.28.0
  #storage
  objectbox: ^4.0.2
  objectbox_flutter_libs: ^4.0.2

  #crypto
  cryptography: ^2.7.0

  #UI
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1

  #other
  path_provider: ^2.1.5
  path: ^1.9.0
  permission_handler: ^11.3.1
  file_picker: ^8.1.4
  open_file: ^3.5.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.0.0
  objectbox_generator: any
  intl_utils: ^2.8.8

dependency_overrides:
  js: ^0.7.1

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/2.0x/
    - assets/3.0x/
  fonts:
    - family: Sansation
      fonts:
        - asset: fonts/sansation/Sansation_Light.ttf
          weight: 300
        - asset: fonts/sansation/Sansation_Regular.ttf
          weight: 400
        - asset: fonts/sansation/Sansation_Bold.ttf
          weight: 700

    - family: NotoSans
      fonts:
        - asset: fonts/notosans/NotoSans-Light.ttf
          weight: 300
        - asset: fonts/notosans/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/notosans/NotoSans-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
